language: cpp
sudo: required
complier:
- g++
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-4.9
      - gcc-4.9
before_install:
  - chmod 777 scripts/install_gtest.sh
install:
  - sudo ./scripts/install_gtest.sh
before_script:
  - chmod 777 scripts/run_tests.sh
  - chmod 777 scripts/build.sh
script: 
  - ./scripts/build.sh
  - ./scripts/run_tests.sh