language: cpp
sudo: required
complier:
- g++
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-4.9
      - gcc-4.9
before_script:
  - cd scripts
  - chmod 777 install_gtest.sh
  - ./install_gtest.sh
  - cd ..
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../build
  - chmod 777 run_tests.sh
  - ./run_tests.sh
